### PR TITLE
GlossHook Update

### PR DESCRIPTION
**Pull request by XMDS**

### CODE REVIEW

**Comment by RusJJ** [comment]
Cant merge it but seems like it works. What was wrong?

**Comment by RusJJ** [comment]
Also, is Gloss::Inst::GetThumb32BranchDestination working? Tried this on BLX, returns 0.

**Comment by RusJJ** [comment]
And another problem: branch hook is adding extra __1__ to the **original**.

**Comment by RusJJ** [comment]
Okay, it's just broken. Please check it's behaviour, a usage of value returned to "original" is 100% unsafe and results in a crash.

**Comment by RusJJ** [comment]
@XMDS branch destination functions are still not working at all. Thumb16 B/B-Cond returning 0, while Thumb32 are PROBABLY working. But they return wrong address...

**Comment by XMDS** [comment]
> @XMDS branch destination functions are still not working at all. Thumb16 B/B-Cond returning 0, while Thumb32 are PROBABLY working. But they return wrong address...

```
if(IsThumbAddr(addr))
```
Yes.  You actually uploaded the thumb address (+1). The thumb address is not detected inside the get branch function. It is only controlled by the extra parameter $THUMB.  It is worth noting that all functions in inst are not tested for thumb.  I'll add it right away.

**Comment by RusJJ** [comment]
> > @XMDS branch destination functions are still not working at all. Thumb16 B/B-Cond returning 0, while Thumb32 are PROBABLY working. But they return wrong address...
> 
> ```
> if(IsThumbAddr(addr))
> ```
> 
> Yes. You actually uploaded the thumb address (+1). The thumb address is not detected inside the get branch function. It is only controlled by the extra parameter $THUMB. It is worth noting that all functions in inst are not tested for thumb. I'll add it right away.

That's why i wrote this code...
```
if(IsThumbAddr(addr))
                {
                    switch(Gloss::Inst::GetBranch(addr, $THUMB))
                    {
                        case Gloss::Inst::branchs::B_COND16:
                        case Gloss::Inst::branchs::B_16:
                            return (uintptr_t)Gloss::Inst::GetThumb16BranchDestination(addr);

                        case Gloss::Inst::branchs::B_COND:
                        case Gloss::Inst::branchs::B:
                        case Gloss::Inst::branchs::BL:
                        case Gloss::Inst::branchs::BLX:
                            return (uintptr_t)Gloss::Inst::GetThumb32BranchDestination(addr);

                        default:
                            return 0;
                    }
                }
                else
                {
                    return (uintptr_t)Gloss::Inst::GetArmBranchDestination(addr);
                }
```

**Comment by XMDS** [comment]
> It just does  not work for some branches. Never for Thumb16, sometimes for Thumb32 (if using address WITHOUT +1)

**Comment by RusJJ** [comment]
> Now it handles thumb addresses (+1)

I was manually removing +1 and it was failing. It still fails for B16.

**Comment by XMDS** [comment]
> > Now it handles thumb addresses (+1)
> 
> I was manually removing +1 and it was failing. It still fails for B16 and B conds.

can you provide your code？
 I tested jumping forward and backward and it works fine

**Comment by RusJJ** [comment]
> I tested jumping forward and backward and it works fine
Are you sure your Gloss::Inst::GetBranch is working?

**Comment by RusJJ** [comment]
Are you ever going to release the source code..?

**Comment by RusJJ** [comment]
lmao, you broke BLX hook again (or maybe it's not BLX hook). Cant even start the game...

**Comment by XMDS** [comment]
> Are you ever going to release the source code..?

It will be open source in version 2.0.

**Comment by XMDS** [comment]
> lmao, you broke BLX hook again (or maybe it's not BLX hook). Cant even start the game...

我不小心进行了构建绝对跳转 LDR PC PC #0... 指令进行了拇指地址修复（-1），现在它工作正常（1.7.5）

**Comment by RusJJ** [comment]
Can you please make sure it works with B16_COND? Maybe it was GetThumb16BranchDestination or maybe "GetBranch", im not sure. Cannot test it now. Thanks for the fix

**Pull request closed without merging**
